export const LEAGUE_TEAM_COUNTS: Record<string, number> = {
  "LaLiga EA Sports": 20,
  "LaLiga Hypermotion": 22,
  "Primera Federación": 20,
  "Segunda Federación": 18,
  "Premier League": 20,
  "Championship": 24,
  "League One": 24,
  "League Two": 24,
  "Bundesliga": 18,
  "2. Bundesliga": 18,
  "3. Liga": 20,
  "Serie A": 20,
  "Serie B": 20,
  "Serie C": 20,
  "Ligue 1": 18,
  "Ligue 2": 20,
  "Liga Portugal": 18,
  "Liga Portugal 2": 18,
  "Eredivisie": 18,
  "Eerste Divisie": 20,
  "Jupiler Pro League": 16,
  "Süper Lig": 19,
  "MLS": 29,
  "Liga MX": 18,
  "Brasileirão": 20,
  "Argentine Primera División": 28,
  "Primeira Liga": 18,
  "Superliga": 16,
  "Ekstraklasa": 18,
  "Super League": 16,
  "Pro League": 16,
  "Eliteserien": 16,
  "Allsvenskan": 16,
  "Veikkausliiga": 12,
  "HNL": 10,
  "SuperLiga": 16,
  "Fortuna Liga": 16,
  "NB I": 12,
  "Premier Division": 10,
  "A-League": 12,
  "Chinese Super League": 16,
  "J1 League": 18,
  "K League 1": 12,
  "Saudi Pro League": 18,
  "Qatar Stars League": 12,
  "A-League Men": 12,
};